---
configure_dotfiles: true
configure_terminal: true
configure_osx: true
configure_extra_packages: true
configure_emacs: true
configure_dock: true

homebrew_installed_packages:
  - ansible
  - git
  - node
  - nvm
  - wget
  - java
  - tmux
  - defaultbrowser
  - dos2unix
  - coreutils
  - emacs-plus@27
  - rbenv
  - ruby-build

homebrew_taps:
  - homebrew/core
  - homebrew/cask
  - d12frosted/emacs-plus

homebrew_cask_apps:
  - docker
  #  - google-chrome
  - spotify
  - vlc
  - postman
  - stats
  - slack
  - hpedrorodrigues/tools/dockutil # temp until dockutil 3.0 is default on homebrew, ref: https://github.com/kcrawford/dockutil/issues/127
  - bitwarden
  # additional
  - quip
  - dcv-viewer

dockitems_remove:
  - Launchpad
  - Mail
  - Maps
  - Reminders
  - Music
  - Podcasts
  - News
  - Keynote
  - Numbers
  - Pages
  # additional
  - TV
  - Photos
  - Calendar
  - Contacts
  - FaceTime
  - Messages

dockitems_persist:
  - name: "App Store"
    path: "/Applications/App Store.app/"
    pos: 1
  - name: "System Preferences"
    path: "/Applications/System Preferences.app/"
    pos: 2
  - name: "Activity Monitor"
    path: "/System/Applications/Utilities/Activity Monitor.app/"
    pos: 3
  - name: "Cisco AnyConnect Secure Mobility Client"
    path: "/System/Applications/Cisco/Cisco AnyConnect Secure Mobility Client.app/"
    pos: 4
  - name: "Google Chrome"
    path: "/Applications/Google Chrome.app/"
    pos: 5
  - name: "Safari"
    path: "/Applications/Safari.app/"
    pos: 6
  - name: "Bitwarden"
    path: "/Applications/Bitwarden.app/"
    pos: 7
  - name: "Microsoft Outlook"
    path: "/Applications/Microsoft Outlook.app/"
    pos: 8
  - name: "Slack"
    path: "/Applications/Slack.app/"
    pos: 9
  - name: "Amazon Chime"
    path: "/Applications/Amazon Chime.app/"
    pos: 10
  - name: "Notes"
    path: "/Applications/Notes.app/"
    pos: 11
  - name: "Quip"
    path: "/Applications/Quip.app/"
    pos: 12
  - name: "Spotify"
    path: "/Applications/Spotify.app/"
    pos: 13
  - name: "Terminal"
    path: "/Applications/Terminal.app/"
    pos: 14
  - name: "Emacs"
    path: "/Applications/Emacs.app/"
    pos: 15
  - name: "Postman"
    path: "/Applications/Postman.app/"
    pos: 16
