---
homebrew_installed_packages:
  # - ansible # Installed via Pip.
  - git
  - node
  - nvm
  - wget
  - java
  - tmux
  - defaultbrowser
  - dos2unix
  # additional
  - wireguard-tools
  
homebrew_cask_apps:
  - docker
  - google-chrome
  - emacs
  - spotify
  - vlc
  - postman
  - stats
  # additional
  - slack
  - bitwarden
  - discord
  - plex
