- name: template packages.nix
  template:
    src: files/nix/packages.nix
    dest: ~/.packages.nix
  register: packages_template

- name: install packages
  command: "~/.nix-profile/bin/nix-env -i -f ~/.packages.nix"
  when: packages_template.changed
