- name: create nix config dir if it does not exist
  file:
    path: /etc/nixos
    state: directory
  become: true

- name: apply nix configuration
  copy:
    src: files/nix/configuration.nix
    dest: /etc/nixos/configuration.nix
  become: true
