---
# TODO: Use sudo once .osx can be run via root with no user interaction.
- name: Run .osx dotfiles.
  command: "{{ osx_script }}"
  changed_when: false

- name: Run .defaultbrowser.scpt dotfiles.
  command: "{{ defaultbrowser_script }} {{defaultbrowser_browser}}"
  changed_when: false
