---
# oh-my-zsh https://github.com/robbyrussell/oh-my-zsh
- local_action: stat path=/tmp/oh-my-zsh-install.sh
  register: oh_my_zsh_install_file

- name: download oh my zsh install script.
  command: wget https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh -O /tmp/oh-my-zsh-install.sh
  register: ohmyzsh_download
  when: oh_my_zsh_install_file.stat.exists is false

- name: clean oh my zsh install script.
  command: dos2unix /tmp/oh-my-zsh-install.sh
  when: ohmyzsh_download.changed

- name: make oh my zsh install script executable
  file:
    dest: /tmp/oh-my-zsh-install.sh
    mode: +x
  when: ohmyzsh_download.changed

- local_action: stat path=~/.oh-my-zsh
  register: oh_my_zsh_folder

- name: run oh my zsh install script.
  command: sh -c /tmp/oh-my-zsh-install.sh
  when: oh_my_zsh_folder.stat.exists is false

# powerlevel10k https://github.com/romkatv/powerlevel10k
- local_action: stat path=~/.oh-my-zsh/custom/themes/powerlevel10k
  register: powerlevel10k_file

- name: install powerlevel10k.
  command: git clone --depth=1 https://github.com/romkatv/powerlevel10k.git ~/.oh-my-zsh/custom/themes/powerlevel10k
  when: powerlevel10k_file.stat.exists is false

# Source code pro font
- local_action: stat path=/Library/Fonts/SourceCodeProForPowerline.otf
  register: powerline_font_file

- name: install Source code pro font.
  command: wget https://raw.githubusercontent.com/powerline/fonts/master/SourceCodePro/Source%20Code%20Pro%20for%20Powerline.otf -O /Library/Fonts/SourceCodeProForPowerline.otf
  when: powerline_font_file.stat.exists is false

# Custom Terminal theme.
- name: Get current Terminal profile.
  command: defaults read com.apple.terminal 'Default Window Settings'
  register: terminal_theme
  changed_when: false
  check_mode: false

- name: Ensure custom Terminal profile is added.
  copy:
    src: files/terminal/Solarized-Dark.terminal
    dest: /tmp/Solarized-Dark.terminal
  changed_when: false
  when: "'Solarized-Dark' not in terminal_theme.stdout"

- name: Ensure custom Terminal profile is added.
  command: open /tmp/Solarized-Dark.terminal
  changed_when: false
  when: "'Solarized-Dark' not in terminal_theme.stdout"

# TODO: This doesn't work in Yosemite. Consider a different solution?
- name: Ensure custom Terminal profile is set as default.
  command: "{{ item }}"
  with_items:
    - defaults write com.apple.terminal 'Default Window Settings' -string Solarized-Dark
    - defaults write com.apple.terminal 'Startup Window Settings' -string Solarized-Dark
  changed_when: false
  when: "'Solarized-Dark' not in terminal_theme.stdout"
