---
# oh-my-zsh https://github.com/robbyrussell/oh-my-zsh
- name: check for zsh folder
  stat:
    path: ~/.oh-my-zsh
  register: oh_my_zsh_folder

- name: install oh my zsh
  block:
    - name: create oh my zsh temp folder
      tempfile:
        state: directory
      register: oh_my_zsh_temp_dir

    - name: download oh my zsh install script.
      command: "wget https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh -O {{oh_my_zsh_temp_dir.path}}/oh-my-zsh-install.sh"

    # don't think this is necessary anymore
    #- name: clean oh my zsh install script.
    #  command: "dos2unix {{ oh_my_zsh_temp_dir.path }}/oh-my-zsh-install.sh"

    - name: make oh my zsh install script executable
      file:
        dest: "{{ oh_my_zsh_temp_dir.path }}/oh-my-zsh-install.sh"
        mode: +x

    - name: run oh my zsh install script.
      command: "sh -c {{ oh_my_zsh_temp_dir.path }}/oh-my-zsh-install.sh"
  when: oh_my_zsh_folder.stat.exists is false

# powerlevel10k https://github.com/romkatv/powerlevel10k
- name: check for powerlevel10k folder
  stat:
    path: ~/.oh-my-zsh/custom/themes/powerlevel10k
  register: powerlevel10k_file

- name: install powerlevel10k.
  command: git clone --depth=1 https://github.com/romkatv/powerlevel10k.git ~/.oh-my-zsh/custom/themes/powerlevel10k
  when: powerlevel10k_file.stat.exists is false

# TODO: install font for linux
  
# Source code pro font
- name: check for source code pro font
  stat:
    path: /Library/Fonts/Source Code Pro for Powerline.otf
  register: powerline_font_file
  when: ansible_os_family == "Darwin"

- name: install Source code pro font.
  command: wget https://raw.githubusercontent.com/powerline/fonts/master/SourceCodePro/Source%20Code%20Pro%20for%20Powerline.otf -O /Library/Fonts/Source\ Code\ Pro\ for\ Powerline.otf
  when: powerline_font_file.stat.exists is false and ansible_os_family == "Darwin"

# dircolors
- name: check for dircolors.
  stat:
    path: ~/.dircolors
  register: dircolors_folder

- name: install dircolors.
  command: wget https://raw.githubusercontent.com/seebi/dircolors-solarized/master/dircolors.256dark -O ~/.dircolors
  when: dircolors_folder.stat.exists is false

# zshenv
- name: template zshenv.
  template:
    src: templates/.zshenv.j2
    dest: ~/.zshenv
  register: zshenv_template

- name: check for zshenv.local.
  stat:
    path: ~/.zshenv.local
  register: zshenv_local_file

- name: create zshenv.local.
  copy:
    src: files/terminal/.zshenv.local
    dest: ~/.zshenv.local
  when: zshenv_local_file.stat.exists is false

# zprofile
- name: template zprofile.
  template:
    src: templates/.zprofile.j2
    dest: ~/.zprofile
  register: zprofile_template

- name: check for zprofile.local.
  stat:
    path: ~/.zprofile.local
  register: zprofile_local_file

- name: create zprofile.local.
  copy:
    src: files/terminal/.zprofile.local
    dest: ~/.zprofile.local
  when: zprofile_local_file.stat.exists is false

- name: exit if zshenv or zprofile changed
  fail: msg="please close this terminal, open a new one, and rerun the playbook. Alternatively you can try omz reload"
  when: zshenv_template.changed or zprofile_template.changed
